import Head from 'next/head';
import { Button } from '@nextui-org/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>k-tech-feed</h1>
        <Button>안녕하세요</Button>
      </main>
    </>
  );
}
